---
Name: goldfinch-nest
---
SilverStripe\Versioned\VersionedGridFieldItemRequest:
  extensions:
    - Goldfinch\Nest\Forms\GridField\GridFieldDetailFormItemRequestExtension

Goldfinch\Nest\Models\NestedObject:
  extensions:
    - SilverStripe\Admin\CMSEditLinkExtension

---
Name: goldfinch-nest-icon
Only:
  moduleexists: "goldfinch/enchantment"
---
Goldfinch\Nest\Pages\Nest:
  icon_class: "bi-file-earmark-post"
