---
Name: goldfinch-nest
---

SilverStripe\Versioned\VersionedGridFieldItemRequest:
  extensions:
    - Goldfinch\Nest\Forms\GridField\GridFieldDetailFormItemRequestExtension

Goldfinch\Nest\Models\NestedObject:
  extensions:
    - SilverStripe\Admin\CMSEditLinkExtension

Goldfinch\Nest\Controllers\NestController:
  extensions:
    - Goldfinch\Seo\Extensions\MetaUniverse
