---
Name: goldfinch-nest
---

SilverStripe\Versioned\VersionedGridFieldItemRequest:
  extensions:
    - 'Goldfinch\Nest\Form\GridField\GridFieldDetailFormItemRequestExtension'

Goldfinch\Nest\Models\NestedObject:
  extensions:
    - SilverStripe\Admin\CMSEditLinkExtension
